import SwiftUI

final class ModifierState: ObservableObject {
    @Published var ctrl = false
    @Published var alt = false
    /// Shift applies only to actions tapped in MobileToolbar. SwiftTerm owns
    /// Shift from the software and hardware keyboards.
    @Published var shift = false

    func consume() -> TerminalInputModifiers {
        var result: TerminalInputModifiers = []
        if ctrl {
            result.insert(.control)
            ctrl = false
        }
        if alt {
            result.insert(.alt)
            alt = false
        }
        if shift {
            result.insert(.shift)
            shift = false
        }
        return result
    }
}

struct TerminalInputModifiers: OptionSet, Equatable {
    let rawValue: UInt8

    static let shift = TerminalInputModifiers(rawValue: 1 << 0)
    static let alt = TerminalInputModifiers(rawValue: 1 << 1)
    static let control = TerminalInputModifiers(rawValue: 1 << 2)
}

/// Keys generated by Handoff's toolbar. Software and hardware keyboard events
/// remain SwiftTerm's responsibility.
enum TerminalInputKey: Equatable {
    case escape
    case interrupt
    case tab
    case enter
    case up
    case down
    case left
    case right
    case home
    case end
    case pageUp
    case pageDown
    case wordLeft
    case wordRight
    case slash
    case dash
    case pipe
}

/// Pure, deterministic xterm encoder for toolbar actions.
enum TerminalInputEncoder {
    static func encode(
        _ key: TerminalInputKey,
        applicationCursor: Bool,
        modifiers: TerminalInputModifiers = []
    ) -> [UInt8] {
        switch key {
        case .up:
            return cursor(final: 0x41, applicationCursor: applicationCursor, modifiers: modifiers)
        case .down:
            return cursor(final: 0x42, applicationCursor: applicationCursor, modifiers: modifiers)
        case .right:
            return cursor(final: 0x43, applicationCursor: applicationCursor, modifiers: modifiers)
        case .left:
            return cursor(final: 0x44, applicationCursor: applicationCursor, modifiers: modifiers)
        case .home:
            return cursor(final: 0x48, applicationCursor: applicationCursor, modifiers: modifiers)
        case .end:
            return cursor(final: 0x46, applicationCursor: applicationCursor, modifiers: modifiers)
        case .pageUp:
            return tildeKey(number: 5, modifiers: modifiers)
        case .pageDown:
            return tildeKey(number: 6, modifiers: modifiers)
        case .tab:
            // Termux treats Shift+Tab as back-tab, ignores Ctrl for Tab, and
            // applies Alt as the usual ESC prefix.
            let bytes: [UInt8] = modifiers.contains(.shift)
                ? [0x1B, 0x5B, 0x5A]
                : [0x09]
            return modifiers.contains(.alt) ? [0x1B] + bytes : bytes
        case .enter:
            let byte: UInt8 = modifiers.contains(.shift) ? 0x0A : 0x0D
            return modifiers.contains(.alt) ? [0x1B, byte] : [byte]
        case .escape:
            return modifiers.contains(.alt) ? [0x1B, 0x1B] : [0x1B]
        case .interrupt:
            return [0x03]
        case .wordLeft:
            return [0x1B, 0x62]
        case .wordRight:
            return [0x1B, 0x66]
        case .slash:
            return character(normal: 0x2F, shifted: 0x3F, modifiers: modifiers)
        case .dash:
            return character(normal: 0x2D, shifted: 0x5F, modifiers: modifiers)
        case .pipe:
            return [0x7C]
        }
    }

    private static func cursor(
        final: UInt8,
        applicationCursor: Bool,
        modifiers: TerminalInputModifiers
    ) -> [UInt8] {
        if !modifiers.isEmpty {
            return csi("1;\(xtermModifierParameter(modifiers))") + [final]
        }
        return [0x1B, applicationCursor ? 0x4F : 0x5B, final]
    }

    private static func tildeKey(number: Int, modifiers: TerminalInputModifiers) -> [UInt8] {
        if modifiers.isEmpty {
            return csi("\(number)~")
        }
        return csi("\(number);\(xtermModifierParameter(modifiers))~")
    }

    private static func character(
        normal: UInt8,
        shifted: UInt8,
        modifiers: TerminalInputModifiers
    ) -> [UInt8] {
        var byte = modifiers.contains(.shift) ? shifted : normal
        if modifiers.contains(.control) {
            byte = controlByte(for: byte)
        }
        return modifiers.contains(.alt) ? [0x1B, byte] : [byte]
    }

    private static func controlByte(for byte: UInt8) -> UInt8 {
        switch byte {
        case 0x3F: // Ctrl-? (Shift-/)
            return 0x7F
        case 0x40...0x5F, 0x60...0x7E:
            return byte & 0x1F
        case 0x2F: // Ctrl-/
            return 0x1F
        default:
            return byte
        }
    }

    private static func xtermModifierParameter(_ modifiers: TerminalInputModifiers) -> Int {
        1
            + (modifiers.contains(.shift) ? 1 : 0)
            + (modifiers.contains(.alt) ? 2 : 0)
            + (modifiers.contains(.control) ? 4 : 0)
    }

    private static func csi(_ suffix: String) -> [UInt8] {
        [0x1B, 0x5B] + Array(suffix.utf8)
    }
}

/// Stable semantic identities prevent SwiftUI from rebuilding unrelated
/// buttons when modifier state changes.
enum TerminalToolbarActionID: String, CaseIterable {
    case escape
    case slash
    case dash
    case home
    case up
    case end
    case paste
    case dismissKeyboard
    case tab
    case control
    case alt
    case shift
    case left
    case down
    case right
    case enter
}

/// The first seven entries in each row are the Android extra-key surface in
/// the same order. iOS-native utilities are appended so the shared muscle
/// memory stays intact without hiding paste or keyboard dismissal.
enum TerminalToolbarLayout {
    static let androidCoreRow1: [TerminalToolbarActionID] = [
        .escape, .slash, .dash, .home, .up, .end, .shift,
    ]
    static let androidCoreRow2: [TerminalToolbarActionID] = [
        .tab, .control, .alt, .left, .down, .right, .enter,
    ]
    static let row1 = androidCoreRow1 + [.paste]
    static let row2 = androidCoreRow2 + [.dismissKeyboard]
}

/// Two-row toolbar of extra keys for terminal use on mobile.
/// Mirrors the Android key surface closely so muscle memory carries over.
struct MobileToolbar: View {
    @ObservedObject var modifiers: ModifierState
    let applicationCursorMode: () -> Bool
    let onKey: (Data) -> Void
    let onPaste: () -> Void
    let onDismissKeyboard: () -> Void

    private let row1 = TerminalToolbarLayout.row1.map { ToolbarKey(id: $0) }
    private let row2 = TerminalToolbarLayout.row2.map { ToolbarKey(id: $0) }

    var body: some View {
        VStack(spacing: 0) {
            Divider()
                .background(Theme.border)

            toolbarRow(row1)
            toolbarRow(row2)
        }
        .background(Theme.surface)
    }

    private func toolbarRow(_ keys: [ToolbarKey]) -> some View {
        HStack(spacing: 0) {
            ForEach(keys) { key in
                ToolbarButton(
                    key: key,
                    isActive: isModifierActive(key.id),
                    onTap: { handleTap(for: key) },
                    onLongPress: { handleLongPress(for: key) }
                )
            }
        }
    }

    private func isModifierActive(_ id: TerminalToolbarActionID) -> Bool {
        switch id {
        case .control:
            return modifiers.ctrl
        case .alt:
            return modifiers.alt
        case .shift:
            return modifiers.shift
        default:
            return false
        }
    }

    private func handleTap(for key: ToolbarKey) {
        switch key.id {
        case .control:
            modifiers.ctrl.toggle()
        case .alt:
            modifiers.alt.toggle()
        case .shift:
            modifiers.shift.toggle()
        case .paste:
            onPaste()
        case .dismissKeyboard:
            onDismissKeyboard()
        default:
            guard let input = key.key else { return }
            send(input)
        }
    }

    private func handleLongPress(for key: ToolbarKey) {
        guard let input = key.longPressKey else {
            handleTap(for: key)
            return
        }
        // Android's extra-key long presses are intrinsic actions (Ctrl-C,
        // pipe, page navigation, or word navigation) and do not consume a
        // sticky modifier. Match that behavior so the next tap still receives
        // any highlighted Ctrl/Alt/Shift state.
        let bytes = TerminalInputEncoder.encode(
            input,
            applicationCursor: applicationCursorMode()
        )
        onKey(Data(bytes))
    }

    private func send(_ input: TerminalInputKey) {
        let activeModifiers = modifiers.consume()
        let bytes = TerminalInputEncoder.encode(
            input,
            applicationCursor: applicationCursorMode(),
            modifiers: activeModifiers
        )
        onKey(Data(bytes))
    }
}

private struct ToolbarButton: View {
    let key: ToolbarKey
    let isActive: Bool
    let onTap: () -> Void
    let onLongPress: () -> Void

    @State private var touchStart: Date?
    @State private var longPressFired = false
    @State private var repeatTask: Task<Void, Never>?

    private let longPressDelay: TimeInterval = 0.45
    private let repeatInterval: UInt64 = 80_000_000

    var body: some View {
        Group {
            if let systemImage = key.systemImage {
                Image(systemName: systemImage)
            } else {
                Text(key.label)
            }
        }
        .font(.system(size: 13, weight: .medium, design: .monospaced))
        .foregroundColor(isActive ? Theme.background : Theme.text)
        .frame(maxWidth: .infinity)
        .frame(height: 44)
        .background(isActive ? Theme.primary : Color.clear)
        .contentShape(Rectangle())
        .accessibilityLabel(key.accessibilityLabel)
        .gesture(
            DragGesture(minimumDistance: 0)
                .onChanged { _ in
                    guard touchStart == nil else { return }
                    touchStart = Date()
                    longPressFired = false
                    if key.longPressKey != nil {
                        repeatTask = Task {
                            try? await Task.sleep(nanoseconds: UInt64(longPressDelay * 1_000_000_000))
                            guard !Task.isCancelled else { return }
                            await MainActor.run {
                                longPressFired = true
                                onLongPress()
                            }
                            guard key.repeatsLongPress else { return }
                            while !Task.isCancelled {
                                try? await Task.sleep(nanoseconds: repeatInterval)
                                guard !Task.isCancelled else { return }
                                await MainActor.run {
                                    onLongPress()
                                }
                            }
                        }
                    }
                }
                .onEnded { _ in
                    let wasLongPress = longPressFired
                    resetTouchState()
                    if !wasLongPress {
                        onTap()
                    }
                }
        )
    }

    private func resetTouchState() {
        repeatTask?.cancel()
        repeatTask = nil
        touchStart = nil
        longPressFired = false
    }
}

private struct ToolbarKey: Identifiable {
    let id: TerminalToolbarActionID
    let label: String
    let key: TerminalInputKey?
    let longPressKey: TerminalInputKey?
    let repeatsLongPress: Bool
    let systemImage: String?
    let accessibilityLabel: String

    init(id: TerminalToolbarActionID) {
        switch id {
        case .escape:
            self.init(id: id, label: "ESC", key: .escape, longPressKey: .interrupt)
        case .slash:
            self.init(id: id, label: "/", key: .slash)
        case .dash:
            self.init(id: id, label: "-", key: .dash, longPressKey: .pipe)
        case .home:
            self.init(id: id, label: "HOME", key: .home)
        case .up:
            self.init(id: id, label: "\u{2191}", key: .up, longPressKey: .pageUp)
        case .end:
            self.init(id: id, label: "END", key: .end)
        case .paste:
            self.init(id: id, label: "PASTE", key: nil, accessibilityLabel: "Paste")
        case .dismissKeyboard:
            self.init(
                id: id,
                label: "KEYBOARD",
                key: nil,
                systemImage: "keyboard.chevron.compact.down",
                accessibilityLabel: "Dismiss keyboard"
            )
        case .tab:
            self.init(id: id, label: "TAB", key: .tab)
        case .control:
            self.init(id: id, label: "CTRL", key: nil)
        case .alt:
            self.init(id: id, label: "ALT", key: nil)
        case .shift:
            self.init(id: id, label: "SHIFT", key: nil)
        case .left:
            self.init(
                id: id,
                label: "\u{2190}",
                key: .left,
                longPressKey: .wordLeft,
                repeatsLongPress: true
            )
        case .down:
            self.init(id: id, label: "\u{2193}", key: .down, longPressKey: .pageDown)
        case .right:
            self.init(
                id: id,
                label: "\u{2192}",
                key: .right,
                longPressKey: .wordRight,
                repeatsLongPress: true
            )
        case .enter:
            self.init(id: id, label: "\u{21B5}", key: .enter)
        }
    }

    init(
        id: TerminalToolbarActionID,
        label: String,
        key: TerminalInputKey?,
        longPressKey: TerminalInputKey? = nil,
        repeatsLongPress: Bool = false,
        systemImage: String? = nil,
        accessibilityLabel: String? = nil
    ) {
        self.id = id
        self.label = label
        self.key = key
        self.longPressKey = longPressKey
        self.repeatsLongPress = repeatsLongPress
        self.systemImage = systemImage
        self.accessibilityLabel = accessibilityLabel ?? label
    }
}
